### ISSUE TITLE
Cannot download / Install Module

### ISSUE THREAD

**Issue by ScottUlmer** [misterpotts/fabricate#68]
setup.js:292 Error: The Fabricate module does not provide a download URL that can be installed
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:2452)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)

**Comment by misterpotts** [comment]
First of all, thanks for the report! It's a strange one, as it has been installed before successfully. Perhaps it is this specific release ([0.7.2](https://github.com/misterpotts/fabricate/releases/tag/0.7.2)), but I'd be surprised. 'module.json' (available [here](https://github.com/misterpotts/fabricate/releases/latest/download/module.json)) does include the [archive download link](https://github.com/misterpotts/fabricate/releases/download/0.7.2/module.zip). 

```json
{
    "manifest": "https://github.com/misterpotts/fabricate/releases/latest/download/module.json",
    "download": "https://github.com/misterpotts/fabricate/releases/download/0.7.2/module.zip"
}
```

This works for me! 🤔 

Whatever the cause, it will be much easier for me to investigate it if you can provide additional details by expanding the description of this Issue. I've included a copy of the "Bug Report" template below. If you could provide me with as much of this detail as possible I'd be very grateful. Even if the fix is "link to manual installation documentation in the readme", these details will help us figure out what's going wrong and improve Fabricate.

```markdown
## Describe the bug

A clear and concise description of what the bug is.

## To Reproduce

Steps to reproduce the behavior:

1. Go to '...'
1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Screenshots

If applicable, add screenshots to help explain your problem.

## Version information

- Foundry version: [e.g. 10]
- Fabricate version: [e.g. 0.7.2]

## Additional context

Add any other contextual information about the problem here.

```

Thanks in advance!

**Comment by misterpotts** [comment]
I think I might have figured it out. Are you downloading the bundle, then using to the downloaded manifest file ('module.json') to install? That file doesn't have the links.

I could do the work to add them (and probably should), however all that will do is go off to download the module from GitHub using the links above!

Manual installation by downloading the archive requires that you drop it (unpacked) into your FoundryVTT modules directory. That's at '<FOUNDRY_INSTALL_PATH>/Data/modules'

**Comment by ScottUlmer** [comment]
Hey yep I was simply going to the root and trying to find a json that looked like a manifest. I believe the link I settled on was https://raw.githubusercontent.com/misterpotts/fabricate/main/package.json.  Sorry, never had to dig into individual versions before, also way for me to be the dumbest person to use your tool. Apologies! The https://github.com/misterpotts/fabricate/releases/latest/download/module.json did work and is now installed. Thank you for your time.

**Comment by misterpotts** [comment]
Not at all! I have added #70 add a reference to the Foundry docs to the FAQ as well as explain that the release `module.json` is the one to use. Later, I'll look at making sure both versions contain the URL.
